### ISSUE TITLE
Android 5 

### ISSUE THREAD

**Issue by janakact** [vicke4/react-native-invoke-app#3]
```
E/RNInvokeApp( 8137): android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
E/RNInvokeApp( 8137):   at android.app.ContextImpl.startActivity(ContextImpl.java:1377)
E/RNInvokeApp( 8137):   at android.app.ContextImpl.startActivity(ContextImpl.java:1357)
E/RNInvokeApp( 8137):   at android.content.ContextWrapper.startActivity(ContextWrapper.java:324)
E/RNInvokeApp( 8137):   at android.content.ContextWrapper.startActivity(ContextWrapper.java:324)
E/RNInvokeApp( 8137):   at com.codegulp.invokeapp.RNInvokeApp.invokeApp(RNInvokeApp.java:55)
E/RNInvokeApp( 8137):   at java.lang.reflect.Method.invoke(Native Method)
E/RNInvokeApp( 8137):   at java.lang.reflect.Method.invoke(Method.java:372)
E/RNInvokeApp( 8137):   at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
E/RNInvokeApp( 8137):   at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
E/RNInvokeApp( 8137):   at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
E/RNInvokeApp( 8137):   at android.os.Handler.handleCallback(Handler.java:815)
E/RNInvokeApp( 8137):   at android.os.Handler.dispatchMessage(Handler.java:104)
```

Expectation:
Application to open 

Reality: 
Nothing happens and above error can be seen in the `adb logcat`.

Android Version: 5
React Native Version: 0.59

**Comment by janakact** [comment]
May be a duplicate of #2
